#+TITLE: Readme

* <2021-08-09 Mon>
** changing l490 sc headers in /legacy_cmp_srt
backup of originals contained in /legacy_cmp_srt_backup


* <2021-08-10 Tue>
** Change headers complete
Significant problems running code
Htop status showed D after 1 pass through loop
Had to restart script and change the file for each file
Tried different mounting options - regular mounting of shared file system lagged linux system very bad
Mounted with ntfs and ntfs-3g still had problems
Tried moving files to vagabond still had problems
Lines 127 and 130 did not have navigation recorded in in the .410 file
Will proceed without using these
*** Navigation information does not exist for the times during line 130, cannot use this line
* Current /*processed directories cannot be used to upload to USGS page due to lack of navigation in headers
   
* <2023-01-24 Tue> 
  - Played with change_sgy_header_L490.py appears to work
  - May still have some problems with navigation being correct in pre-stack data
  - Will wait to meet with ABG tomorrow to discuss what to do.


* <2023-01-25 Wed> 
  - Checked the L490 stuff on Reveal w/ ABG and after some digging found that
    the problem was with how I was looping through traces. This did not
    account for gaps in the data, so it scrunched some navigation to earlier 
    ffid numbers, and left the end of line without corrected navigation
  - debugged this code with debug_change_sgy_header_L490.py on test line 125
  - Then cleaned up this code and looped through lines with problems
    fixed_change_sgy_header_L490.py

* <2023-03-07 Tue> Fix errors on other lines 
  - Per ABG email there are additional navigation errors on many other lines
    See L490SC_nav2_issues.csv
  - Will see how the fixed code does with 128a first. I'll use debug_change_sgy_header_L490.py
  - Decided to try to populate navigation based on the shot point from the nav 
    (410 file) The shotpoints (ffids) are nearly complete but are missing ~1-15
    at either edge. I'm going to ignore this for now and see if other problems 
    arise.
  - Incorporated these changes into fixed2_change_sgy_header_L490.py
  - Have run 101, 102, 103 later. Each line 
    takes about 800 seconds to process

* <2023-03-08 Wed> finish the rest of the lines 
  - [3:] in the loop
  - Seems to slow down significantly after a few lines
  - Ran through 107a restart wsl2 [7:] need to start at 109a
  - This line has taken ~70 minutes already
 
